# -*- coding: utf-8 -*-
"""AirQuality_ML_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iDEEFOex7XlpaQDMk-a6AfG9wSm-XQ5

# 🌫️ Air Quality ML — Data Preparation & Model Training
**Project:** Indoor Air Pollution Monitoring Station  
**Notebook version:** 1.0  
Notebook workflow:
1. Install dependencies
2. Fetch historical weather data (Open-Meteo)
3. Load & clean your EEA station CSV files
4. Load & clean your sensor CSV
5. Merge everything into one daily training dataset
6. Train two models: Prophet (temp/humidity forecast) + Random Forest (danger classifier)
7. Evaluate both models
8. Export lightweight `.pkl` files ready for the Raspberry Pi

> **How to use:** Upload CSV files when prompted in Section 3 & 4, then run all cells top to bottom (`Runtime → Run all`).

## 1. Install & Import Dependencies
"""

# Install required packages
!pip install prophet scikit-learn pandas numpy requests matplotlib seaborn joblib -q

import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings
import os
from datetime import datetime, timedelta
from io import StringIO

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
print(" All packages loaded successfully")

"""## 2. Fetch Historical Weather Data (Open-Meteo)
Free, no API key needed. Fetches hourly temperature, humidity, and weather code
for Timișoara going back to Jan 2024, then resamples to daily averages.

"""

# Configuration
LAT        = 45.7489    # Timișoara latitude
LON        = 21.2087    # Timișoara longitude
START_DATE = "2021-01-01"
END_DATE   = datetime.today().strftime("%Y-%m-%d")

print(f"Fetching Open-Meteo weather data: {START_DATE} → {END_DATE}")

url = (
    f"https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={LAT}&longitude={LON}"
    f"&start_date={START_DATE}&end_date={END_DATE}"
    f"&hourly=temperature_2m,relative_humidity_2m,weathercode"
    f"&timezone=Europe%2FBucharest"
)

resp = requests.get(url, timeout=30)
resp.raise_for_status()
data = resp.json()

weather_hourly = pd.DataFrame({
    "datetime":    pd.to_datetime(data["hourly"]["time"]),
    "temp_c":      data["hourly"]["temperature_2m"],
    "humidity":    data["hourly"]["relative_humidity_2m"],
    "weathercode": data["hourly"]["weathercode"],
})

# Resample to daily
weather_hourly["date"] = weather_hourly["datetime"].dt.date
weather_daily = weather_hourly.groupby("date").agg(
    temp_c_mean   = ("temp_c",      "mean"),
    temp_c_max    = ("temp_c",      "max"),
    temp_c_min    = ("temp_c",      "min"),
    humidity_mean = ("humidity",    "mean"),
    weathercode   = ("weathercode", lambda x: x.mode()[0]),  # most common code
).reset_index()
weather_daily["date"] = pd.to_datetime(weather_daily["date"])

# Map weather codes to a simple is_rainy flag
# WMO codes 51-99 = precipitation
weather_daily["is_rainy"] = weather_daily["weathercode"].apply(
    lambda c: 1 if c >= 51 else 0
)

print(f" Weather data fetched: {len(weather_daily)} days")
print(weather_daily.tail(5).to_string(index=False))

"""## 3. Load & Clean EEA Station CSV Files
Upload **all** your EEA CSV files when the file picker appears.  
The code auto-detects pollutant codes from the filename — no manual renaming needed.

Files expected (upload as many as you have):
- `converted_SPO-RO0193A_00001_100.csv` → SO₂
- `converted_SPO-RO0193A_00020_100.csv` → NO₂
- `converted_SPO-RO0194A_00001_100.csv` → SO₂
- `converted_SPO-RO0194A_00007_100.csv` → O₃
- `converted_SPO-RO0194A_00020_100.csv` → NO₂
- `converted_SPO-RO0196A_00001_100.csv` → SO₂
- `converted_SPO-RO0196A_00010_100.csv` → CO
- `converted_SPO-RO0196A_00020_100.csv` → NO₂
- `converted_SPO-RO0197A_00010_100.csv` → CO
- `converted_SPO-RO0197A_00020_100.csv` → NO₂

"""

from google.colab import files as colab_files

POLLUTANT_CODES = {
    "00001": "so2",
    "00007": "o3",
    "00010": "co",
    "00020": "no2",
}

# WHO / EU danger thresholds (daily average, µg/m³ or mg/m³ as per unit)
EEA_THRESHOLDS = {
    "so2":  125.0,   # µg/m³  EU 24h limit
    "o3":    120.0,  # µg/m³  EU 8h max (used as daily proxy)
    "co":      10.0, # mg/m³  EU 8h limit
    "no2":    200.0, # µg/m³  EU 1h limit (strict)
}

print(" Upload your EEA CSV files...")
uploaded = colab_files.upload()

eea_frames = {}  # pollutant_name -> list of DataFrames

for fname, content in uploaded.items():
    # Extract pollutant code from filename
    parts = fname.replace(".csv","").split("_")
    poll_code = None
    for p in parts:
        if p in POLLUTANT_CODES:
            poll_code = p
            break

    if poll_code is None:
        print(f"   Could not identify pollutant in '{fname}' — skipping")
        continue

    poll_name = POLLUTANT_CODES[poll_code]
    df = pd.read_csv(StringIO(content.decode("utf-8")))

    # Keep only valid rows
    df = df[df["Validity"] == 1].copy()
    df = df[df["Value"] != -9900].copy()
    df = df[df["Value"] >= 0].copy()          # drop negative noise values

    if len(df) == 0:
        print(f"  '{fname}' has no valid rows after filtering — skipping")
        continue

    df["date"] = pd.to_datetime(df["Start"]).dt.normalize()
    df = df[["date", "Value"]].rename(columns={"Value": poll_name})

    eea_frames.setdefault(poll_name, []).append(df)
    print(f"  {fname:55s} → {poll_name:4s}  ({len(df):,} valid rows)")

print()

# Merge all frames for each pollutant into daily averages
eea_daily_parts = []

for poll_name, frames in eea_frames.items():
    combined = pd.concat(frames, ignore_index=True)
    # Average across stations for the same day
    daily = combined.groupby("date")[poll_name].mean().reset_index()
    eea_daily_parts.append(daily)
    print(f"  {poll_name}: {len(daily)} days  |  mean={daily[poll_name].mean():.3f}  max={daily[poll_name].max():.3f}")

# Outer-join all pollutants on date
from functools import reduce
eea_daily = reduce(lambda a, b: pd.merge(a, b, on="date", how="outer"), eea_daily_parts)
eea_daily = eea_daily.sort_values("date").reset_index(drop=True)

print(f"\n EEA daily dataset: {len(eea_daily)} days, columns: {list(eea_daily.columns)}")

"""## 4. Load & Clean Your Sensor CSV
Upload the CSV exported from your Raspberry Pi (the file with MQ135, MQ3, MQ6, MQ7, MQ8 columns).

"""

# Danger thresholds for MQ sensors (PPM)
SENSOR_THRESHOLDS = {
    "MQ135_ppm": 200.0,   # NO₂ / general AQ proxy  (EU NO₂ hourly limit)
    "MQ3_ppm":  1000.0,   # VOCs / alcohol           (OSHA TWA)
    "MQ6_ppm":  1000.0,   # LPG / butane             (~20% LEL)
    "MQ7_ppm":    35.0,   # CO                       (WHO 1h guideline)
    "MQ8_ppm":  1000.0,   # Hydrogen                 (~25% LEL)
}

print(" Please upload sensor CSV file...")
uploaded_sensor = colab_files.upload()

sensor_fname = list(uploaded_sensor.keys())[0]
sensor_raw = pd.read_csv(StringIO(uploaded_sensor[sensor_fname].decode("utf-8")))

print(f"Raw sensor rows: {len(sensor_raw)}")
print(f"Columns: {list(sensor_raw.columns)}")

# datetime column
def parse_sensor_date(row):
    try:
        day_num = str(row["Day"]).split()[-1]   # "Sunday 24" -> "24"
        return pd.to_datetime(f"{row['Year']} {row['Month']} {day_num}", format="%Y %B %d")
    except:
        return pd.NaT

sensor_raw["date"] = sensor_raw.apply(parse_sensor_date, axis=1)

# Drop rows with bad temperature (0.0°C sensor failure)
sensor_raw = sensor_raw[sensor_raw["Temperature_C"] > 1.0].copy()

# Drop rows with missing dates
sensor_raw = sensor_raw.dropna(subset=["date"])

# PPM columns
ppm_cols = ["MQ135_ppm", "MQ3_ppm", "MQ6_ppm", "MQ7_ppm", "MQ8_ppm"]

# Daily aggregation
sensor_daily = sensor_raw.groupby("date").agg(
    **{col + "_mean": (col, "mean") for col in ppm_cols},
    **{col + "_max":  (col, "max")  for col in ppm_cols},
    temp_sensor_mean  = ("Temperature_C", "mean"),
    humidity_sensor   = ("Humidity",      "mean"),
    n_readings        = ("MQ135_ppm",     "count"),
).reset_index()

# Build danger label:
# 1 if ANY sensor mean exceeds its threshold on that day
def is_dangerous(row):
    for col, thresh in SENSOR_THRESHOLDS.items():
        mean_col = col + "_mean"
        if mean_col in row and pd.notna(row[mean_col]) and row[mean_col] > thresh:
            return 1
    return 0

sensor_daily["danger"] = sensor_daily.apply(is_dangerous, axis=1)

print(f"\n✅ Sensor daily dataset: {len(sensor_daily)} days")
print(f"   Danger days: {sensor_daily['danger'].sum()} / {len(sensor_daily)}")
print(sensor_daily.to_string(index=False))

"""## 5. Merge Everything into One Training Dataset
We outer-join weather + EEA + sensor on date, then forward-fill small gaps.

"""

# Merge weather + EEA
df = pd.merge(weather_daily, eea_daily, on="date", how="left")

# Merge sensor data
df = pd.merge(df, sensor_daily, on="date", how="left")

df = df.sort_values("date").reset_index(drop=True)

# Forward-fill EEA gaps up to 3 days
eea_cols = [c for c in df.columns if c in ["so2","o3","co","no2"]]
df[eea_cols] = df[eea_cols].fillna(method="ffill", limit=3)

# Add time features
df["dayofyear"]  = df["date"].dt.dayofyear
df["month"]      = df["date"].dt.month
df["weekofyear"] = df["date"].dt.isocalendar().week.astype(int)
df["season"]     = df["month"].map({
    12:0, 1:0, 2:0,   # winter
     3:1, 4:1, 5:1,   # spring
     6:2, 7:2, 8:2,   # summer
     9:3,10:3,11:3,   # autumn
})

# Lag features for temp & humidity (yesterday's values)
df["temp_lag1"]     = df["temp_c_mean"].shift(1)
df["temp_lag7"]     = df["temp_c_mean"].shift(7)
df["humidity_lag1"] = df["humidity_mean"].shift(1)

# Lag features for EEA pollutants
for col in eea_cols:
    df[col + "_lag1"] = df[col].shift(1)
    df[col + "_lag7"] = df[col].shift(7)

# Rolling 7-day means
df["temp_roll7"]     = df["temp_c_mean"].rolling(7, min_periods=1).mean()
df["humidity_roll7"] = df["humidity_mean"].rolling(7, min_periods=1).mean()
for col in eea_cols:
    df[col + "_roll7"] = df[col].rolling(7, min_periods=1).mean()

print(f" Merged dataset: {len(df)} days  |  {len(df.columns)} columns")
print(f"   Date range: {df['date'].min().date()} → {df['date'].max().date()}")
print(f"\nColumn list:")
for col in df.columns:
    missing = df[col].isna().sum()
    print(f"  {col:35s}  missing: {missing:4d} / {len(df)}")

"""## 6. Quick Exploratory Plots"""

fig, axes = plt.subplots(3, 2, figsize=(16, 12))
fig.suptitle("Timișoara — Daily Averages Overview", fontsize=14, fontweight="bold")

plot_pairs = [
    ("date", "temp_c_mean",    "Temperature (°C)",       "tab:red"),
    ("date", "humidity_mean",  "Humidity (%)",            "tab:blue"),
    ("date", "no2",            "NO₂ (µg/m³)",            "tab:orange"),
    ("date", "co",             "CO (mg/m³)",              "tab:brown"),
    ("date", "so2",            "SO₂ (µg/m³)",            "tab:purple"),
    ("date", "o3",             "O₃ (µg/m³)",             "tab:green"),
]

for ax, (x, y, title, color) in zip(axes.flat, plot_pairs):
    if y in df.columns:
        sub = df[["date", y]].dropna()
        ax.plot(sub["date"], sub[y], color=color, linewidth=0.8, alpha=0.8)
        ax.set_title(title)
        ax.set_xlabel("")
        ax.tick_params(axis="x", rotation=30)
    else:
        ax.set_title(f"{title} — no data")
        ax.axis("off")

plt.tight_layout()
plt.savefig("overview_plots.png", dpi=120, bbox_inches="tight")
plt.show()
print(" Plot saved as overview_plots.png")

"""## 7. Train Prophet Models (Temperature & Humidity Forecast)
Prophet is designed for time series with seasonality and missing data.  
We train one model per target. Each produces a **7-day ahead forecast**.

"""

from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error

def train_prophet(df, target_col, label):
    """Train a Prophet model and return (model, forecast_df, metrics)."""
    sub = df[["date", target_col]].dropna().rename(
        columns={"date": "ds", target_col: "y"}
    )

    if len(sub) < 14:
        print(f"  ⚠️  Not enough data for {label} ({len(sub)} rows) — skipping")
        return None, None, None

    # Train / test split  last 14 days as hold-out
    split = sub["ds"].max() - pd.Timedelta(days=14)
    train = sub[sub["ds"] <= split]
    test  = sub[sub["ds"] >  split]

    model = Prophet(
        yearly_seasonality  = True,
        weekly_seasonality  = True,
        daily_seasonality   = False,
        seasonality_mode    = "additive",
        changepoint_prior_scale = 0.05,
    )
    model.fit(train)

    # Predict on test + 7 days ahead
    future = model.make_future_dataframe(periods=14 + 7)
    forecast = model.predict(future)

    # Metrics on hold-out
    merged = test.merge(forecast[["ds","yhat"]], on="ds")
    if len(merged) > 0:
        mae  = mean_absolute_error(merged["y"], merged["yhat"])
        rmse = mean_squared_error(merged["y"], merged["yhat"]) ** 0.5
        print(f"  {label:30s}  MAE={mae:.3f}  RMSE={rmse:.3f}  (hold-out {len(merged)} days)")
    else:
        print(f"  {label:30s}  trained (no hold-out overlap)")

    return model, forecast, sub

print("Training Prophet models...")
model_temp,     fc_temp,     sub_temp     = train_prophet(df, "temp_c_mean",   "Temperature (°C)")
model_humidity, fc_humidity, sub_humidity = train_prophet(df, "humidity_mean", "Humidity (%)")
print("\n Prophet training complete")

# Plot Prophet forecasts
def plot_prophet(model, forecast, sub, label, color):
    if model is None:
        return
    fig, ax = plt.subplots(figsize=(14, 4))
    ax.plot(sub["ds"], sub["y"], ".", color=color, markersize=4, label="Actual", alpha=0.7)
    fc_future = forecast[forecast["ds"] > sub["ds"].max()]
    ax.plot(forecast["ds"], forecast["yhat"], color=color, linewidth=1, alpha=0.5, label="Fitted")
    ax.fill_between(fc_future["ds"], fc_future["yhat_lower"], fc_future["yhat_upper"],
                    alpha=0.2, color=color)
    ax.plot(fc_future["ds"], fc_future["yhat"], color=color, linewidth=2, label="7-day forecast")
    ax.axvline(sub["ds"].max(), color="grey", linestyle="--", linewidth=0.8)
    ax.set_title(f"Prophet forecast — {label}")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"prophet_{label.replace(' ','_').replace('(','').replace(')','')}.png",
                dpi=120, bbox_inches="tight")
    plt.show()

plot_prophet(model_temp,     fc_temp,     sub_temp,     "Temperature C",  "tab:red")
plot_prophet(model_humidity, fc_humidity, sub_humidity, "Humidity pct",   "tab:blue")

"""## 8. Train Random Forest Danger Classifier
Predicts whether a future day is likely to have **dangerous air quality**
(any sensor exceeding its threshold).

Since sensor data is limited, we use EEA pollutant readings + weather as features,
with the sensor-derived `danger` label where available, and an EEA-derived label
for all other days.

"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

#  Build classifier label
# Priority: use sensor-derived label if available, else derive from EEA thresholds
def eea_danger(row):
    checks = {
        "no2": EEA_THRESHOLDS.get("no2", 200),
        "co":  EEA_THRESHOLDS.get("co",   10),
        "so2": EEA_THRESHOLDS.get("so2",  125),
        "o3":  EEA_THRESHOLDS.get("o3",   120),
    }
    for col, thresh in checks.items():
        if col in row and pd.notna(row[col]) and row[col] > thresh:
            return 1
    return 0

df["danger_label"] = df.apply(
    lambda row: int(row["danger"]) if pd.notna(row.get("danger")) else eea_danger(row),
    axis=1
)

print(f"Danger label distribution:")
print(df["danger_label"].value_counts().to_string())
print(f"  ({df['danger_label'].mean()*100:.1f}% dangerous days)")

#  Feature selection
feature_cols = [
    "temp_c_mean", "temp_c_max", "temp_c_min",
    "humidity_mean", "is_rainy",
    "dayofyear", "month", "season", "weekofyear",
    "temp_lag1", "temp_lag7", "temp_roll7",
    "humidity_lag1", "humidity_roll7",
]

# Add EEA features if available
for col in ["no2","co","so2","o3"]:
    for suffix in ["", "_lag1", "_lag7", "_roll7"]:
        full = col + suffix
        if full in df.columns:
            feature_cols.append(full)

# Add sensor PPM features if available
for col in ["MQ135_ppm_mean","MQ3_ppm_mean","MQ6_ppm_mean","MQ7_ppm_mean","MQ8_ppm_mean"]:
    if col in df.columns:
        feature_cols.append(col)

# Remove duplicates
feature_cols = list(dict.fromkeys(feature_cols))

# Build X, y — drop rows missing label or all features
clf_df = df[feature_cols + ["danger_label"]].dropna(subset=["danger_label"])

# Fill remaining NaN with column medians
clf_df = clf_df.copy()
for col in feature_cols:
    if col in clf_df.columns:
        clf_df[col] = clf_df[col].fillna(clf_df[col].median())

X = clf_df[feature_cols]
y = clf_df["danger_label"].astype(int)

print(f"\nClassifier dataset: {len(X)} rows  |  {len(feature_cols)} features")
print(f"Features used: {feature_cols}")

#  Train & evaluate
rf = RandomForestClassifier(
    n_estimators     = 200,
    max_depth        = 6,
    min_samples_leaf = 3,
    class_weight     = "balanced",   # handles imbalanced danger/safe classes
    random_state     = 42,
    n_jobs           = -1,
)

# Cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf, X, y, cv=cv, scoring="f1")
print(f"Cross-val F1 scores: {cv_scores.round(3)}")
print(f"Mean F1: {cv_scores.mean():.3f}  ±  {cv_scores.std():.3f}")

# Fit on full data for deployment
rf.fit(X, y)

# Feature importances
importances = pd.Series(rf.feature_importances_, index=feature_cols).sort_values(ascending=False)
print(f"\nTop 10 most important features:")
print(importances.head(10).round(4).to_string())

# Confusion matrix on full data (informational only)
y_pred = rf.predict(X)
print(f"\nClassification report (full data, informational):")
print(classification_report(y, y_pred, target_names=["Safe","Danger"]))

# Plot feature importances
fig, ax = plt.subplots(figsize=(10, 6))
importances.head(15).plot(kind="barh", ax=ax, color="steelblue")
ax.set_title("Random Forest — Top 15 Feature Importances")
ax.invert_yaxis()
plt.tight_layout()
plt.savefig("feature_importances.png", dpi=120, bbox_inches="tight")
plt.show()

"""## 9. Generate 7-Day Predictions"""

# Build a 7-day future DataFrame using Prophet forecasts + last known EEA values
last_known = df.iloc[-1]
today = df["date"].max()

future_rows = []
for i in range(1, 8):
    future_date = today + pd.Timedelta(days=i)
    row = {"date": future_date}

    # Get Prophet temperature/humidity for this date
    if fc_temp is not None:
        fc_row_t = fc_temp[fc_temp["ds"] == future_date]
        row["temp_c_mean"]   = fc_row_t["yhat"].values[0]   if len(fc_row_t) else last_known["temp_c_mean"]
        row["temp_c_max"]    = fc_row_t["yhat_upper"].values[0] if len(fc_row_t) else last_known["temp_c_max"]
        row["temp_c_min"]    = fc_row_t["yhat_lower"].values[0] if len(fc_row_t) else last_known["temp_c_min"]
    else:
        row["temp_c_mean"] = last_known["temp_c_mean"]
        row["temp_c_max"]  = last_known["temp_c_max"]
        row["temp_c_min"]  = last_known["temp_c_min"]

    if fc_humidity is not None:
        fc_row_h = fc_humidity[fc_humidity["ds"] == future_date]
        row["humidity_mean"] = fc_row_h["yhat"].values[0] if len(fc_row_h) else last_known["humidity_mean"]
    else:
        row["humidity_mean"] = last_known["humidity_mean"]

    # Time features
    row["dayofyear"]  = future_date.dayofyear
    row["month"]      = future_date.month
    row["weekofyear"] = future_date.isocalendar()[1]
    row["season"]     = {12:0,1:0,2:0,3:1,4:1,5:1,6:2,7:2,8:2,9:3,10:3,11:3}[future_date.month]
    row["is_rainy"]   = 0  # unknown; conservative assumption

    # Lag/roll features from last known data
    row["temp_lag1"]     = last_known["temp_c_mean"]
    row["temp_lag7"]     = df.iloc[-7]["temp_c_mean"] if len(df) >= 7 else last_known["temp_c_mean"]
    row["temp_roll7"]    = df["temp_c_mean"].tail(7).mean()
    row["humidity_lag1"] = last_known["humidity_mean"]
    row["humidity_roll7"]= df["humidity_mean"].tail(7).mean()

    for col in ["no2","co","so2","o3"]:
        row[col]            = last_known.get(col, np.nan)
        row[col + "_lag1"]  = last_known.get(col, np.nan)
        row[col + "_lag7"]  = df.iloc[-7].get(col, np.nan) if len(df) >= 7 else np.nan
        row[col + "_roll7"] = df[col].tail(7).mean() if col in df.columns else np.nan

    for col in ["MQ135_ppm_mean","MQ3_ppm_mean","MQ6_ppm_mean","MQ7_ppm_mean","MQ8_ppm_mean"]:
        row[col] = last_known.get(col, np.nan)

    future_rows.append(row)

future_df = pd.DataFrame(future_rows)

# Fill any remaining NaN with training medians
for col in feature_cols:
    if col in future_df.columns:
        future_df[col] = future_df[col].fillna(X[col].median())
    else:
        future_df[col] = X[col].median()

# Predict danger
future_df["danger_predicted"]     = rf.predict(future_df[feature_cols])
future_df["danger_probability"]   = rf.predict_proba(future_df[feature_cols])[:, 1].round(3)

# Get Prophet temp/humidity
if fc_temp is not None:
    fc_temp_future = fc_temp[fc_temp["ds"].isin(future_df["date"])]
    future_df = future_df.merge(
        fc_temp_future[["ds","yhat","yhat_lower","yhat_upper"]].rename(
            columns={"ds":"date","yhat":"temp_forecast","yhat_lower":"temp_low","yhat_upper":"temp_high"}),
        on="date", how="left"
    )

if fc_humidity is not None:
    fc_hum_future = fc_humidity[fc_humidity["ds"].isin(future_df["date"])]
    future_df = future_df.merge(
        fc_hum_future[["ds","yhat","yhat_lower","yhat_upper"]].rename(
            columns={"ds":"date","yhat":"hum_forecast","yhat_lower":"hum_low","yhat_upper":"hum_high"}),
        on="date", how="left"
    )

output_cols = ["date","temp_forecast","temp_low","temp_high","hum_forecast","hum_low","hum_high",
               "danger_predicted","danger_probability"]
output_cols = [c for c in output_cols if c in future_df.columns]

print("\n📅 7-Day Prediction:")
print(future_df[output_cols].to_string(index=False))

future_df[output_cols].to_csv("predictions_7day.csv", index=False)
print("\n Saved to predictions_7day.csv")

"""## 10. Export Models for Raspberry Pi
Saves lightweight `.pkl` files you copy to the Pi.  
Also saves `feature_cols.pkl` so `predict.py` knows which features to build.

"""

import joblib, json

os.makedirs("models", exist_ok=True)

# Save Random Forest
joblib.dump(rf, "models/rf_danger_classifier.pkl")
print("✅ Saved models/rf_danger_classifier.pkl")

# Save Prophet models
if model_temp is not None:
    joblib.dump(model_temp,     "models/prophet_temperature.pkl")
    print("✅ Saved models/prophet_temperature.pkl")

if model_humidity is not None:
    joblib.dump(model_humidity, "models/prophet_humidity.pkl")
    print("✅ Saved models/prophet_humidity.pkl")

# Save feature list and thresholds
meta = {
    "feature_cols":       feature_cols,
    "sensor_thresholds":  SENSOR_THRESHOLDS,
    "eea_thresholds":     EEA_THRESHOLDS,
    "trained_on":         datetime.today().strftime("%Y-%m-%d"),
    "training_rows":      len(X),
}
with open("models/model_meta.json", "w") as f:
    json.dump(meta, f, indent=2)
print("✅ Saved models/model_meta.json")

# Download all model files
print("\n Downloading model files...")
colab_files.download("models/rf_danger_classifier.pkl")
if model_temp:     colab_files.download("models/prophet_temperature.pkl")
if model_humidity: colab_files.download("models/prophet_humidity.pkl")
colab_files.download("models/model_meta.json")
colab_files.download("predictions_7day.csv")
print("\n✅ All files downloaded. Copy them to your Raspberry Pi in a /models/ folder.")

"""## 11. Monthly Retraining (run this cell each month)
Just re-run this single cell after adding new sensor CSV rows.  
It re-fetches the latest weather, reloads your CSVs, retrains, and re-exports.

"""

#  MONTHLY RETRAIN — re-run this cell only
# 1. Re-upload your updated sensor CSV
print(" Upload your latest sensor CSV for retraining...")
new_sensor = colab_files.upload()

# 2. Re-fetch latest weather (extends automatically to today)
print("Fetching latest weather data...")
END_DATE = datetime.today().strftime("%Y-%m-%d")
url_retrain = (
    f"https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={LAT}&longitude={LON}"
    f"&start_date={START_DATE}&end_date={END_DATE}"
    f"&hourly=temperature_2m,relative_humidity_2m,weathercode"
    f"&timezone=Europe%2FBucharest"
)
resp2 = requests.get(url_retrain, timeout=30)
data2 = resp2.json()
wh2 = pd.DataFrame({
    "datetime":    pd.to_datetime(data2["hourly"]["time"]),
    "temp_c":      data2["hourly"]["temperature_2m"],
    "humidity":    data2["hourly"]["relative_humidity_2m"],
    "weathercode": data2["hourly"]["weathercode"],
})
wh2["date"] = wh2["datetime"].dt.date
weather_daily_new = wh2.groupby("date").agg(
    temp_c_mean   = ("temp_c",   "mean"),
    temp_c_max    = ("temp_c",   "max"),
    temp_c_min    = ("temp_c",   "min"),
    humidity_mean = ("humidity", "mean"),
    weathercode   = ("weathercode", lambda x: x.mode()[0]),
).reset_index()
weather_daily_new["date"]     = pd.to_datetime(weather_daily_new["date"])
weather_daily_new["is_rainy"] = weather_daily_new["weathercode"].apply(lambda c: 1 if c>=51 else 0)
print(f"  Weather updated: {len(weather_daily_new)} days")

# 3. Reload sensor with same parsing as Section 4
sname = list(new_sensor.keys())[0]
s2 = pd.read_csv(StringIO(new_sensor[sname].decode("utf-8")))
s2["date"] = s2.apply(parse_sensor_date, axis=1)
s2 = s2[s2["Temperature_C"] > 1.0].dropna(subset=["date"])
sensor_daily_new = s2.groupby("date").agg(
    **{col+"_mean": (col,"mean") for col in ppm_cols},
    **{col+"_max":  (col,"max")  for col in ppm_cols},
    temp_sensor_mean = ("Temperature_C","mean"),
    humidity_sensor  = ("Humidity","mean"),
    n_readings       = ("MQ135_ppm","count"),
).reset_index()
sensor_daily_new["danger"] = sensor_daily_new.apply(is_dangerous, axis=1)
print(f"  Sensor updated: {len(sensor_daily_new)} days")

# 4. Re-merge (EEA stays the same — re-run Section 3 if you have new EEA files)
df2 = pd.merge(weather_daily_new, eea_daily, on="date", how="left")
df2 = pd.merge(df2, sensor_daily_new, on="date", how="left")
df2 = df2.sort_values("date").reset_index(drop=True)
df2[eea_cols] = df2[eea_cols].fillna(method="ffill", limit=3)
df2["dayofyear"]  = df2["date"].dt.dayofyear
df2["month"]      = df2["date"].dt.month
df2["weekofyear"] = df2["date"].dt.isocalendar().week.astype(int)
df2["season"]     = df2["month"].map({12:0,1:0,2:0,3:1,4:1,5:1,6:2,7:2,8:2,9:3,10:3,11:3})
df2["temp_lag1"]     = df2["temp_c_mean"].shift(1)
df2["temp_lag7"]     = df2["temp_c_mean"].shift(7)
df2["humidity_lag1"] = df2["humidity_mean"].shift(1)
df2["temp_roll7"]     = df2["temp_c_mean"].rolling(7, min_periods=1).mean()
df2["humidity_roll7"] = df2["humidity_mean"].rolling(7, min_periods=1).mean()
for col in eea_cols:
    df2[col+"_lag1"]  = df2[col].shift(1)
    df2[col+"_lag7"]  = df2[col].shift(7)
    df2[col+"_roll7"] = df2[col].rolling(7, min_periods=1).mean()

# 5. Retrain both models
print("Retraining Prophet...")
model_temp2,     fc_temp2,     sub_temp2     = train_prophet(df2, "temp_c_mean",  "Temperature (°C)")
model_humidity2, fc_humidity2, sub_humidity2 = train_prophet(df2, "humidity_mean","Humidity (%)")

print("Retraining Random Forest...")
df2["danger_label"] = df2.apply(
    lambda row: int(row["danger"]) if pd.notna(row.get("danger")) else eea_danger(row), axis=1)
clf_df2 = df2[feature_cols + ["danger_label"]].dropna(subset=["danger_label"]).copy()
for col in feature_cols:
    clf_df2[col] = clf_df2[col].fillna(clf_df2[col].median())
X2 = clf_df2[feature_cols]
y2 = clf_df2["danger_label"].astype(int)
rf2 = RandomForestClassifier(n_estimators=200, max_depth=6, min_samples_leaf=3,
                              class_weight="balanced", random_state=42, n_jobs=-1)
rf2.fit(X2, y2)
cv2 = cross_val_score(rf2, X2, y2, cv=StratifiedKFold(5, shuffle=True, random_state=42), scoring="f1")
print(f"  Retrained RF — Mean F1: {cv2.mean():.3f}")

# 6. Re-export
joblib.dump(rf2, "models/rf_danger_classifier.pkl")
if model_temp2:     joblib.dump(model_temp2,     "models/prophet_temperature.pkl")
if model_humidity2: joblib.dump(model_humidity2, "models/prophet_humidity.pkl")
meta2 = {**meta, "trained_on": datetime.today().strftime("%Y-%m-%d"), "training_rows": len(X2)}
with open("models/model_meta.json","w") as f: json.dump(meta2, f, indent=2)

colab_files.download("models/rf_danger_classifier.pkl")
if model_temp2:     colab_files.download("models/prophet_temperature.pkl")
if model_humidity2: colab_files.download("models/prophet_humidity.pkl")
colab_files.download("models/model_meta.json")
print("\n Retrained models downloaded. Replace the .pkl files on your Raspberry Pi.")