import 'dart:async';
import 'package:flutter/material.dart';
import '../theme.dart';
import '../widgets/common.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  static const _total = 8;
  final _controller = PageController();
  int _current = 0;
  Timer? _timer;

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(const Duration(seconds: 5), (_) {
      if (!_controller.hasClients) return;
      final next = (_current + 1) % _total;
      _controller.animateToPage(next,
          duration: const Duration(milliseconds: 400), curve: Curves.easeInOut);
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 28),
      children: [
        const PageTitle('Welcome'),
        const SizedBox(height: 16),
        SurfaceCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'The present project is an air quality monitoring station that has '
                'been assembled using a set of MQ gas sensors, a module to monitor '
                'temperature and humidity, and a module for the detection of sound. '
                'All the data collected by this air quality monitoring station is '
                'stored in a database.',
                style: AppText.body(15),
              ),
              const SizedBox(height: 14),
              Text(
                'Use the Data page to explore live and historical sensor readings '
                'with interactive charts, filtered by date and location. The '
                'Predictions page surfaces machine-learning forecasts derived from '
                'the collected data.',
                style: AppText.body(15),
              ),
            ],
          ),
        ),
        const SizedBox(height: 20),
        _carousel(),
        const SizedBox(height: 20),
        SurfaceCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('About the station', style: AppText.heading(19)),
              const SizedBox(height: 12),
              Text(
                'AirNest is built around a Raspberry Pi 4B and monitors indoor air '
                'quality using five MQ-series gas sensors: the MQ-135 (equivalent '
                'CO\u2082 / general air quality), MQ-3 (alcohol and benzene), MQ-6 '
                '(LPG and butane), MQ-7 (carbon monoxide), and MQ-8 (hydrogen). A '
                'DHT11 module records temperature and humidity, and a KY-037 sensor '
                'tracks ambient sound levels and sudden sound events.',
                style: AppText.body(15),
              ),
              const SizedBox(height: 12),
              Text(
                'Readings are taken every 30 minutes and sent to a cloud database. '
                'The Predictions page shows a daily 7-day forecast generated by two '
                'machine learning models: Prophet, used for temperature and humidity '
                'forecasting, and a Random Forest classifier, which predicts whether '
                'air quality conditions are likely to reach a danger level based on '
                'historical sensor data and weather forecasts from Open-Meteo.',
                style: AppText.body(15),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _carousel() {
    return ClipRRect(
      borderRadius: BorderRadius.circular(14),
      child: AspectRatio(
        aspectRatio: 4 / 3,
        child: Stack(
          fit: StackFit.expand,
          children: [
            PageView.builder(
              controller: _controller,
              itemCount: _total,
              onPageChanged: (i) => setState(() => _current = i),
              itemBuilder: (_, i) => Image.asset(
                'assets/images/stationPic${i + 1}.jpeg',
                fit: BoxFit.cover,
              ),
            ),
            // Counter pill
            Positioned(
              top: 10,
              right: 10,
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.55),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text('${_current + 1} / $_total',
                    style: AppText.body(11, color: Colors.white)),
              ),
            ),
            // Dots
            Positioned(
              bottom: 10,
              left: 0,
              right: 0,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(_total, (i) {
                  final active = i == _current;
                  return GestureDetector(
                    onTap: () => _controller.animateToPage(i,
                        duration: const Duration(milliseconds: 350),
                        curve: Curves.easeInOut),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 250),
                      margin: const EdgeInsets.symmetric(horizontal: 3),
                      width: active ? 20 : 8,
                      height: 8,
                      decoration: BoxDecoration(
                        color: active
                            ? Colors.white
                            : Colors.white.withOpacity(0.5),
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                  );
                }),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
